[workspace]
authors = ["Michael Hess <michaelhess17@yahoo.com>"]
channels = ["conda-forge"]
name = "Controller"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"

[pypi-dependencies]
pip = ">=25.0.1, <26"
